#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2025 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require_relative '../shared/unittest'
require 'yaml'

$unit_test = 0
require_relative '../lib/openapi/sourcetools/apiobjects'
include OpenAPISourceTools

$context = 'same'
assert(ApiObjects.same(1, 'b'), false, 'Number is not string')
assert(ApiObjects.same({ 'b' => 1 }, 'b'), false, 'Hash is not string')
assert(ApiObjects.same(1, { 'b' => 1 }), false, 'Number is not Hash')
assert(ApiObjects.same(1, 1), true, 'Equal numbers')
a = { a: 5, b: [ 1, 2 ] }
b = { a: 5, b: 'b' }
assert(ApiObjects.same(a, b), false, 'Different types')
b = { a: 5, b: [ 1 ] }
assert(ApiObjects.same(a, b), false, 'Different lengths')
b = { a: 5, b: [ 1, 2 ], c: 'c' }
assert(ApiObjects.same(a, b), false, 'Different keys')
b = { a: 5, b: [ 1, 2 ] }
assert(ApiObjects.same(a, b), true, 'Same contents')
b = { a: 5, b: [ 1, 2 ], 'summary' =>'foo' }
assert(ApiObjects.same(a, b), true, 'Same contents ignoring summary')
b = { a: 5, b: [ 1, 2 ], 'description' => 'foo' }
assert(ApiObjects.same(a, b), true, 'Same contents ignoring description')
b = { a: 5, b: [ 1, 2 ], 'summary' => 'foo', 'description' => 'bar' }
assert(ApiObjects.same(a, b), true, 'Same contents ignoring description and summary')

$context = 'reference'
a = { a: 5, b: [ 1, 2 ] }
b = { a: 5, b: 'b' }
s = { 'bref' => b }
path = 'testing'
r = ApiObjects.reference(a, s, path)
assert(s.size, 2, 'New name added')
r = ApiObjects.reference(a.merge({ 'summary' => 'foo' }), s, path)
r2 = ApiObjects.reference(a, s, path)
assert(r, r2, 'Same object yields same reference')
assert(s.size, 2, 'No new name added')
r = ApiObjects.reference(b, s, path)
assert(s.size, 2, 'No new name added either')
s = { 'bref' => b }
prefix = 'Prefix'
path = 'testing'
r = ApiObjects.reference(b, s, 'testing', Set.new(%w[summary description]), prefix)
assert(s.size, 1, 'No new name added with prefix')
r = ApiObjects.reference(a, s, 'testing', Set.new(%w[summary description]), prefix)
assert(s.size, 2, 'New reference added with prefix')
assert(r.start_with?("#{path}/#{prefix}"), true, 'Reference starts with prefix')

$context = 'Components.reference'
path = 'testing'
prefix = 'Prefix'
cmp = ApiObjects::Components.new(path, prefix)
a = { a: 5, b: [ 1, 2 ] }
b = { a: 5, b: 'b' }
cmp.items['bref'] = b
r = cmp.reference(a)
s = cmp.items
assert(s.size, 2, 'New name added')
r = cmp.reference(a.merge({ 'summary' => 'foo' }))
r2 = cmp.reference(a)
assert(r, r2, 'Same object yields same reference')
assert(s.size, 2, 'No new name added')
r = cmp.reference(b)
assert(s.size, 2, 'No new name added either')
cmp = ApiObjects::Components.new(path, prefix)
cmp.items['bref'] = b
r = cmp.reference(b)
s = cmp.items
assert(s.size, 1, 'No new name added with prefix')
r = cmp.reference(a)
assert(s.size, 2, 'New reference added with prefix')
assert(r.start_with?("#{path}/#{prefix}"), true, 'Reference starts with prefix')

$context = 'Components.add_schema_name'
path = 'testing'
prefix = 'Prefix'
cmp = ApiObjects::Components.new(path, prefix)
cmp.add_schema_name('name')
assert(cmp.schema_names.member?('name'), true, 'Schema name in set')
assert(cmp.schema_names.member?('sdohfg'), false, 'Schema name not in set')

$context = 'Components.store_anchor'
path = 'testing'
prefix = 'Prefix'
cmp = ApiObjects::Components.new(path, prefix)
cmp.store_anchor({})
assert(cmp.anchor2ref.empty?, true, 'Not anchor, not added')
obj = { '$anchor' => 'name' }
cmp.store_anchor(obj, 'ref')
assert(cmp.anchor2ref[obj['$anchor']], 'ref', 'name mapped to given ref')
begin
  cmp.store_anchor(obj)
  assert(true, false, 'Exception not raised')
rescue Exception
  assert(true, true, 'Exception raised')
end
obj = { '$anchor' => 'name2', '$ref' => 'ref2' }
cmp.store_anchor(obj)
assert(cmp.anchor2ref[obj['$anchor']], obj['$ref'], 'name2 mapped to obj ref')

$context = 'Components.alter_anchors'
path = 'testing'
prefix = 'Prefix'
cmp = ApiObjects::Components.new(path, prefix)
cmp.add_schema_name('existing')
cmp.store_anchor({ '$anchor' => 'name' }, 'ref')
cmp.store_anchor({ '$anchor' => 'existing' }, 'ref2')
assert(cmp.anchor2ref.size, 2, 'size 2')
assert(cmp.anchor2ref['name'], 'ref', 'name to ref')
assert(cmp.anchor2ref['existing'], 'ref2', 'existing to ref2')
cmp.alter_anchors
assert(cmp.anchor2ref.size, 2, 'size unchanged')
assert(cmp.anchor2ref['name'], cmp.ref_string('name'), 'name to ref string')
assert(cmp.anchor2ref['existing'], 'ref2', 'existing unchanged')

$context = 'Components.anchor_ref_replacement'
assert(cmp.anchor_ref_replacement('#other'), '#other', 'absent not changed')
assert(cmp.anchor_ref_replacement('#name'), cmp.ref_string('name'), 'name found')
assert(cmp.anchor_ref_replacement('#existing'), 'ref2', 'existing found')

$context = 'operation_objects'
doc = YAML.safe_load(%(---
test1:
  parameters:
  - "$ref": "#/components/parameters/Parameter0x"
  get:
    tags:
    - something
    summary: Hapefjda asdoifjh a pasjd
    description: |
      Hpsafjapsfj oasdifjaosdkfj psdofjpsdajf psdojöasJ
      LAKSNDFKJbade asdvjkasdölm psdjölsdk
    operationId: getSomething
    responses:
      '200':
        "$ref": "#/components/responses/Something"
      '403':
        "$ref": "#/components/responses/Error"
      '404':
        "$ref": "#/components/responses/Error"
      '500':
        "$ref": "#/components/responses/Error"
  put:
    operationId: putSomething
    requestBody:
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Something"
      required: true
    responses:
      '200':
        "$ref": "#/components/responses/Something"
      '403':
        "$ref": "#/components/responses/Error"
      '404':
        "$ref": "#/components/responses/Error"
      '409':
        "$ref": "#/components/responses/Error"
      '500':
        "$ref": "#/components/responses/Error"
  something:
    summary: Blahljadskjfhadlvkj
    responses:
      '204':
        "$ref": "#/components/responses/Empty"
      '403':
        "$ref": "#/components/responses/Error"
      '404':
        "$ref": "#/components/responses/Error"
      '409':
        "$ref": "#/components/responses/Error"
      '500':
        "$ref": "#/components/responses/Error"
test2:
  parameters:
  - "$ref": "#/components/parameters/Parameter0x"
  - "$ref": "#/components/parameters/Parameter1x"
  summary: Text
  description: More text
  op1:
    operationId: getAccess
  op2:
    requestBody:
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Put"
      required: true
  op3:
    responses:
      '204':
        "$ref": "#/components/responses/Empty"
      '403':
        "$ref": "#/components/responses/Error"
      '404':
        "$ref": "#/components/responses/Error"
      '500':
        "$ref": "#/components/responses/Error"
  op4:
    callbacks:
      name: {}
))
oos = ApiObjects.operation_objects(doc['test1'])
assert(oos.size, 3, '3 objects')
assert(oos.key?('get'), true, 'has get')
assert(oos.key?('put'), true, 'has put')
assert(oos.key?('something'), true, 'has something')
oos = ApiObjects.operation_objects(doc['test2'])
assert(oos.size, 4, '4 objects')
assert(oos.key?('op1'), true, 'has op1')
assert(oos.key?('op2'), true, 'has op2')
assert(oos.key?('op3'), true, 'has op3')
assert(oos.key?('op4'), true, 'has op4')

$context = 'ServerVariableObject'
doc = YAML.safe_load(%(---
srv1:
- url: http://example.com/{var}
  variables:
    var:
      default: "a"
      enum: ["a", "b"]
- url: http://example.com/{var2}
  variables:
    var2:
      default: "c"
      enum: ["c", "d"]
srv2:
- url: http://example.com/{var}
  variables:
    var:
      default: "a"
      enum: ["a", "b"]
srv3:
- url: http://example.com/{var2}
  variables:
    var2:
      default: "c"
))
svo = ApiObjects::ServerVariableObject.new('var', doc['srv1'].first.dig('variables', 'var'))
assert(svo.name, 'var', 'name is right')
assert(svo.default, 'a', 'default is right')
assert(svo.enum, %w[a b], 'enum is right')
svo2 = ApiObjects::ServerVariableObject.new('var2', doc['srv3'].first.dig('variables', 'var2'))
assert(svo2.enum, [], 'enum is empty')

$context = 'ServerVariableObject.<=>'
assert(svo <=> svo2, -1, 'svo < svo2')
svo3 = ApiObjects::ServerVariableObject.new('var', doc['srv2'].first.dig('variables', 'var'))
assert(svo3 <=> svo, 0, 'svo3 == svo')
assert(svo <=> svo, 0, 'svo == svo')
assert(svo2 <=> svo3, 1, 'svo3 < svo2')

$context = 'ServerObject'
so = ApiObjects::ServerObject.new(doc['srv1'].first)
assert(so.url, 'http://example.com/{var}', 'url ok')
assert(so.variables.size, 1, 'has variable')
assert(so.variables.first.name, 'var', 'variable name ok')
assert(so.variables.first.default, 'a', 'variable default ok')
assert(so.variables.first.enum, %w[a b], 'variable enum ok')

$context = 'ServerObject.<=>'
so2 = ApiObjects::ServerObject.new(doc['srv1'].last)
assert(so2 <=> so, -1, 'so < so2')
so3 = ApiObjects::ServerObject.new(doc['srv2'].first)
assert(so3 <=> so, 0, 'so == so3')
so4 = ApiObjects::ServerObject.new(doc['srv3'].first)
assert(so2 <=> so4, 1, 'so4 > so2')

$context = 'ServerAlternatives'
sa1 = ApiObjects::ServerAlternatives.new(doc['srv1'])
assert(sa1.servers.size, 2, 'all servers present')
assert(sa1.servers.first.url, 'http://example.com/{var2}', 'sorted')

$context = 'ServerAlternatives.<=>'
sa2 = ApiObjects::ServerAlternatives.new(doc['srv2'])
sa3 = ApiObjects::ServerAlternatives.new(doc['srv3'])
assert(sa1 <=> sa2, -1, 'sa1 < sa2')
assert(sa2 <=> sa3, 1, 'sa2 > sa3')

$context = 'SecurityScheme.<=>'
akh = {
  'type' => 'apiKey',
  'in' => 'header',
  'name' => 'apih'
}
akq = {
  'type' => 'apiKey',
  'in' => 'query',
  'name' => 'apiq'
}
ss1 = ApiObjects::SecurityScheme.new('akh', akh)
ss2 = ApiObjects::SecurityScheme.new('akq', akq)
assert(ss1.name, 'akh', 'name copied')
assert(ss1.scheme, akh, 'scheme copied')
assert(ss1 <=> ss2, -1, 'ss1 < ss2')
assert(ss2 <=> ss1, 1, 'ss2 > ss1')

$context = 'SecurityRequirementObject'
h = {
  'type' => 'http',
  'scheme' => 'Bearer'
}
ss3 = ApiObjects::SecurityScheme.new('http', h)
oa = {
  'type' => 'oauth2',
  'flows' => {
    'implicit' => {
      'authorizationUrl' => 'https://www.skjfhaksfjdhf.com/oauth/authorize'
    },
    'password' => {
      'tokenUrl' => 'https://www.skjfhaksfjdhf.com/oauth/token',
      'scopes' => {}
    },
    'clientCredentials' => {
      'tokenUrl' => 'https://www.skjfhaksfjdhf.com/oauth/token'
    },
    'authorizationCode' => {
      'authorizationUrl' => 'https://www.skjfhaksfjdhf.com/oauth/authorize',
      'tokenUrl' => 'https://www.skjfhaksfjdhf.com/oauth/token'
    }
  }
}
ss4 = ApiObjects::SecurityScheme.new('oauth2', oa)
oidc = {
  'type' => 'openIdConnect',
  'openIdConnectUrl' => 'https://www.skjfhaksfjdhf.com/.well-known/openid-configuration'
}
ss5 = ApiObjects::SecurityScheme.new('oidc', oidc)
schemes = {
  'akh' => ss1,
  'akq' => ss2,
  'http' => ss3,
  'oauth2' => ss4,
  'oidc' => ss5
}
sro1 = ApiObjects::SecurityRequirementObject.new({ 'akh' => [] }, schemes)
assert(sro1.extras[:headers], { akh['name'] => [] }, 'Header parameter')
assert(sro1.extras.key?(:query), false, 'no query')
sro2 = ApiObjects::SecurityRequirementObject.new({ 'akq' => [] }, schemes)
assert(sro2.extras[:query], { akq['name'] => [] }, 'query parameter')
assert(sro2.extras.key?(:headers), false, 'no headers')
sro3 = ApiObjects::SecurityRequirementObject.new({ 'http' => [] }, schemes)
assert(sro3.extras[:headers], { 'authorization' => [] }, 'http authorization')
assert(sro3.extras.key?(:query), false, 'no query')
sro4 = ApiObjects::SecurityRequirementObject.new({ 'oauth2' => [ 'scope' ] }, schemes)
assert(sro4.extras[:headers], { 'authorization' => [ 'scope' ] }, 'oauth2 authorization')
assert(sro4.extras.key?(:query), false, 'no query')
s = %w[scope scope2]
sro5 = ApiObjects::SecurityRequirementObject.new({ 'oidc' => s }, schemes)
assert(sro5.extras[:headers], { 'authorization' => s }, 'oidc authorization')
assert(sro5.extras.key?(:query), false, 'no query')
sro6 = ApiObjects::SecurityRequirementObject.new({ 'akq' => [], 'http' => s }, schemes)
assert(sro6.extras[:query], { akq['name'] => [] }, 'query parameter too')
assert(sro6.extras[:headers], { 'authorization' => s }, 'http authorization too')

$context = 'SecurityRequirementObject.<=>'
assert(sro1 <=> sro6, -1, 'smaller first')
assert(sro1 <=> sro2, -1, 'key order')
sro7 = ApiObjects::SecurityRequirementObject.new({ 'akq' => [ 'scope' ], 'http' => s }, schemes)
assert(sro7 <=> sro6, 1, 'scope order')

$context = 'SecurityAlternatives'
sa1 = ApiObjects::SecurityAlternatives.new([sro1], schemes)
assert(sa1.sros, [sro1], 'sros set')
assert(sa1.schemes, schemes, 'schemes set')

$context = 'SecurityAlternatives.<=>'
sa2 = ApiObjects::SecurityAlternatives.new([sro6], schemes)
sa3 = ApiObjects::SecurityAlternatives.new([sro1], schemes)
assert(sa1 <=> sa2, -1, 'smaller first')
assert(sa1 <=> sa3, 0, 'equal')

exit $unit_test
