#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require 'yaml'
include Test::Unit::Assertions

load '../bin/openapi-oftypes'

class OfTypesTest < Test::Unit::TestCase
  def test_name_string
    assert_equal(name_string(''), '', 'Nothing')
    assert_equal(name_string('a'), 'a', 'Single')
    assert_equal(name_string('a/b/c'), 'c', 'Deep')
  end

  def schemas
    YAML.safe_load(%(---
String:
  type: string
String2:
  type: string
  pattern: '^[0-9]+$'
Number:
  type: number
NotObject:
  type: Number
AB:
  type: object
  properties:
    a:
      $ref: "#/components/schemas/String"
    b:
      $ref: "#/components/schemas/Number"
  required:
    - a
AC:
  type: object
  properties:
    a:
      $ref: "#/components/schemas/String"
    c:
      $ref: "#/components/schemas/String"
  required:
    - a
BC:
  type: object
  properties:
    b:
      $ref: "#/components/schemas/Number"
    c:
      $ref: "#/components/schemas/Number"
  required:
    - b
BC2:
  type: object
  properties:
    b:
      $ref: "#/components/schemas/String"
    c:
      $ref: "#/components/schemas/Number"
  required:
    - b
BC3:
  type: object
  properties:
    b:
      $ref: "#/components/schemas/String"
    c:
      $ref: "#/components/schemas/Unknown"
  required:
    - b
D:
  type: object
  properties:
    d:
      $ref: "#/components/schemas/NotObject"
))
  end

  def test_merge
    s = schemas
    combo = {}
    item0 = s['AB']
    assert_equal(merge(combo, item0), true, 'Merge to empty')
    item = s['BC']
    assert_equal(merge(combo, item), true, 'Merge')
    assert_equal(combo['properties'].size, 3, 'All properties')
    assert_equal(combo['required'], ['a', 'b'], 'Added b to required')
    assert_equal(combo.dig('properties', 'b', '$ref'), '#/components/schemas/Number', 'Still Number type')
    assert_equal(combo.dig('properties', 'c', '$ref'), '#/components/schemas/Number', 'c is Number type')
    combo = {}
    merge(combo, s['AB'])
    assert_equal(merge(combo, s['BC2']), false, 'Type conflict')
  end

  def ref(name)
    { '$ref' => name }
  end

  def test_all_of
    s = schemas
    m = all_of([ ref('AB'), ref('BC') ], s, 'A')
    assert_equal(m.is_a?(Hash), true, 'Merged type')
    assert_equal(m.size, 3, 'New property')
    assert_equal(m['required'], ['a', 'b'], 'Added b to required')
    assert_equal(m.dig('properties', 'b', '$ref'), '#/components/schemas/Number', 'Still Number type')
    assert_equal(m.dig('properties', 'c', '$ref'), '#/components/schemas/Number', 'c is Number type')
    m = all_of([ ref('AB'), ref('BC'), ref('BC2') ], s, 'A')
    assert_equal(m, false, 'Type conflict')
    m = all_of([ ref('BC3') ], s, 'A')
    assert_equal(m.is_a?(Hash), true, 'Missing schema not detected')
    m = all_of([ ref('NotObject') ], s, 'A')
    assert_equal(m, false, 'Not an object')
  end

  def test_distinguishable
    s = schemas
    assert_equal(distinguishable(s['AB'], s['BC'], s), true, 'Different required fields')
    assert_equal(distinguishable(s['AB'], s['AB'], s), false, 'Identical')
    assert_equal(distinguishable(s['AB'], s['AC'], s), false, 'Difference in optional field')
    assert_equal(distinguishable(s['String'], s['Number'], s), true, 'Difference in type')
    assert_equal(distinguishable(s['String'], s['String2'], s), true, 'Difference in fields')
  end

  def test_one_of
  end
end
