#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require 'yaml'
require_relative '../lib/openapi/sourcetools/task'
include Test::Unit::Assertions
include OpenAPISourceTools

module Gen
  attr_accessor :t
  module_function :t
  module_function :t=
  attr_accessor :x
  module_function :x
  module_function :x=

  def self.context_binding
    binding
  end
end

class TaskTest < Test::Unit::TestCase
  def get_content(name)
    `cat #{name}`
  end

  def test_initialize
    begin
      t = Task.new(nil, nil, nil)
    rescue Exception => e
      assert_equal(e.is_a?(ArgumentError), true, 'No template info raises ArgumentError')
    end
    tn = '../test-generate/unittest-task-ok.erb'
    t = Task.new('src', nil, tn)
    assert_equal(t.src, 'src', 'Source set')
    assert_equal(t.template_name, tn, 'Template name set')
    c = get_content(tn)
    assert_equal(t.template, c, 'Template loaded')
    assert_equal(t.name.nil?, true, 'No name')
    assert_equal(t.executable, false, 'Not executable')
    assert_equal(t.discard, false, 'Not discarded')
    assert_equal(t.x.nil?, true, 'x not set')
    t = Task.new('src', c, tn)
    assert_equal(t.src, 'src', 'Source set')
    assert_equal(t.template_name, tn, 'Template name set')
    assert_equal(t.template, c, 'Template stored')
  end

  def test_internal_generate
    tn = '../test-generate/unittest-task-ok.erb'
    t = Task.new('src', nil, tn)
    Gen.t = t
    t.x = { 'out' => 'ok' }
    r = t.internal_generate(Gen.context_binding)
    assert_equal(r.strip!, t.x['out'], 'Returns expected value')
    tn = '../test-generate/unittest-task-error.erb'
    t = Task.new('src', nil, tn)
    Gen.t = t
    begin
      r = t.internal_generate(Gen.context_binding)
      assert_equal(true, false, 'Exception not raised')
    rescue Exception
      assert_equal(true, true, 'Exception raised')
    end
  end

  def test_generate
    tn = '../test-generate/unittest-task-ok.erb'
    t = Task.new('src', nil, tn)
    Gen.t = t
    t.x = { 'out' => 'ok' }
    r = t.generate(Gen.context_binding)
    assert_equal(r.strip!, t.x['out'], 'Returns expected value')
    tn = '../test-generate/unittest-task-error.erb'
    t = Task.new('src', nil, tn)
    Gen.t = t
    r = t.generate(Gen.context_binding)
    assert_equal(r.is_a?(Integer), true, 'Internal exception handled')
  end

  def test_output_name
    tn = '../test-generate/unittest-task-ok.erb'
    c = get_content(tn)
    t = Task.new('src', nil, tn)
    Gen.t = t
    t.x = { 'out' => 'ok' }
    r = t.generate(Gen.context_binding)
    assert_equal(t.name, t.x['out'], 'Output name present')
    assert_equal(t.output_name, t.name, 'Output name returned')
    t = Task.new('src', nil, tn)
    Gen.t = t
    r = t.generate(Gen.context_binding)
    assert_equal(t.name.nil?, true, 'Output name not set')
    assert_equal(t.output_name, File.basename(tn), 'Template name used')
    t = Task.new('src', c, nil)
    Gen.t = t
    r = t.generate(Gen.context_binding)
    assert_equal(t.name.nil?, true, 'Output name not set')
    assert_equal(t.output_name.nil?, true, 'No template name to use')
  end

  def test_write_task
    begin
      t = WriteTask.new(nil, nil)
    rescue Exception => e
      assert_equal(e.is_a?(ArgumentError), true, 'nil arguments raise ArgumentError')
    end
    begin
      t = WriteTask.new(nil, 'contents')
    rescue Exception => e
      assert_equal(e.is_a?(ArgumentError), true, 'nil name raises ArgumentError')
    end
    begin
      t = WriteTask.new('name', nil)
    rescue Exception => e
      assert_equal(e.is_a?(ArgumentError), true, 'nil contents raise ArgumentError')
    end
    t = WriteTask.new('name', 'contents')
    assert_equal(t.name, 'name', 'Name set')
    assert_equal(t.output_name, t.name, 'output_name ok')
    assert_equal(t.generate(nil), 'contents', 'Contents returned')
    assert_equal(t.executable, false, 'Not executable')
    assert_equal(t.system, false, 'Not system task')
  end

  def test_restore_processor_storage
    t = RestoreProcessorStorage.new()
    assert_equal(t.system, true, 'System task')
    assert_equal(t.discard, true, 'Discards output')
    Gen.x = []
    t.generate(nil)
    assert_equal(Gen.x.is_a?(Hash), true, 'Gen.x is a Hash after generate')
    assert_equal(Gen.x.empty?, true, 'Gen.x empty after generate')
  end
end
