#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require_relative '../lib/openapi/sourcetools/generate'
include Test::Unit::Assertions

class GenerateTest < Test::Unit::TestCase
  def ebo(s)
    OpenAPISourceTools::executable_bits_on(s.to_i(8)).to_s(8)
  end

  def test_executable_bits_on
    m = ebo('100644')
    assert_equal(m, '100755', 'all exe on')
    m = ebo('100640')
    assert_equal(m, '100750', 'ug exe on')
    m = ebo('100400')
    assert_equal(m, '100500', 'u exe on')
    m = ebo('111111')
    assert_equal(m, '111111', 'unchanged')
    m = ebo('444444')
    assert_equal(m, '444555', 'a exe on')
    m = ebo('400')
    assert_equal(m, '500', 'short u exe on')
    m = ebo('666')
    assert_equal(m, '777', 'all rwx')
    m = ebo('754')
    assert_equal(m, '755', 'o exe on')
    m = ebo('755')
    assert_equal(m, '755', 'unchanged')
    m = ebo('40')
    assert_equal(m, '50', 'too short but exe on')
  end
end
