#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require 'yaml'
include Test::Unit::Assertions

load '../bin/openapi-checkschemas'

class CheckSchemasTest < Test::Unit::TestCase
  def ref(path, name)
    "#{path}/#{name}"
  end

  def test_typesame
    ign = Set.new(%w[summary description])
    assert_equal(typesame('a', 'b', ign), false, 'Different strings are not equal')
    assert_equal(typesame('a', 'a', ign), true, 'Same strings are equal')
    assert_equal(typesame({ a: 1 }, [ 'b' ], ign), false, 'Hash and array not equal')
    a = YAML.safe_load(%(
---
type: object
required:
- a
properties:
  a:
    $ref: 'reference'
))
    assert_equal(typesame(a, a, ign), true, 'Schema equals itself')
    b = YAML.safe_load(%(
---
type: object
required:
- b
properties:
  b:
    $ref: 'reference'
))
    assert_equal(typesame(a, b, ign), true, 'Schemas equal, changed property name')
    b = YAML.safe_load(%(
---
type: object
required:
- b
properties:
  b:
    $ref: 'reference'
    #{ign.to_a.first}: ignored
))
    assert_equal(typesame(a, b, ign), true, 'Schemas equal, ignored field')
    b = YAML.safe_load(%(
---
type: object
properties:
  a:
    $ref: 'reference'
))
    assert_equal(typesame(a, b, ign), false, 'Schemas not equal, not required field')
    assert_equal(typesame(b, a, ign), false, 'Schemas not equal, reverse order')
    a = YAML.safe_load(%(
---
type: object
properties:
  a:
    $ref: 'reference'
))
    b = YAML.safe_load(%(
---
type: object
properties:
  b:
    $ref: 'reference'
))
    assert_equal(typesame(a, b, ign), true, 'Schemas equal, not required')
    assert_equal(typesame(b, a, ign), true, 'Schemas equal, not required reversed')
    b = YAML.safe_load(%(
---
type: object
required:
- c
properties:
  b:
    $ref: 'reference'
  c:
    type: string
))
    assert_equal(typesame(a, b, ign), false, 'Schemas not equal, extra field')
    assert_equal(typesame(b, a, ign), false, 'Schemas not equal, extra field reversed')
  end
end
