#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require_relative '../lib/openapi/sourcetools/common'
include Test::Unit::Assertions
include OpenAPISourceTools

class CommonTest < Test::Unit::TestCase
  def test_aargh
    assert_equal(Common.aargh('message').nil?, true, 'Default return value')
    assert_equal(Common.aargh('message2', 1), 1, 'Return value')
  end

  def test_yesno
    assert_equal(Common.yesno(true), 'yes', 'True returns yes')
    assert_equal(Common.yesno(false), 'no', 'False returns no')
  end

  def test_bury
    obj = { a: { c: 'c' } }
    path = [ :a, :b ]
    Common.bury(obj, path, 'b')
    assert_equal(obj.dig(*path), 'b', 'New key inserted')
    obj = { a: { c: {} } }
    path = [ :a, :c, :d ]
    Common.bury(obj, path, 'd')
    assert_equal(obj.dig(*path), 'd', 'New item found')
    obj = {}
    Common.bury(obj, path, 'd')
    assert_equal(obj.dig(*path), 'd', 'New items along path found')
  end

  def test_ensure_separate
    doc = Common.load_source('test-retained.yaml')
    begin
      d = YAML.dump(Common.ensure_separate(doc))
      YAML.safe_load(d)
      assert_equal(true, true, 'No exception')
    rescue e
      assert_equal(true, false, "raised an exception, #{e}")
    end
  end

  def test_out
    Common::Out.put('visible')
    assert_equal(Common::Out.count, 1, 'First message')
    Common::Out.quiet = true
    Common::Out.put('not visible')
    assert_equal(Common::Out.count, 2, 'Second message')
  end
end
