#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require 'yaml'
require_relative '../lib/openapi/sourcetools/helper'
include Test::Unit::Assertions
include OpenAPISourceTools

class HelperTest < Test::Unit::TestCase
  def doc1
    YAML.safe_load(%(
---
name: top
children:
  name: single
  children:
  - name: first
    children:
    - name: first2
  - name: second
offspring:
- name: third
- name: fourth
))
  end

  def test_store_parents_parent
    d = doc1
    h = Helper.new(d)
    assert_equal(h.parent(d).nil?, true, 'Top level no parent')
    assert_equal(h.parent(d['children']), d, 'single parent is top')
    d['offspring'].each do |offs|
      assert_equal(h.parent(offs), d, "Offspring #{offs['name']} parent is top")
    end
    p = d.dig('children')
    c = p.dig('children')[0]
    assert_equal(h.parent(c), p, "Child #{c['name']} parent is #{p['name']}")
    c = p.dig('children')[1]
    assert_equal(h.parent(c), p, "Child #{c['name']} parent is #{p['name']}")
    p = d.dig('children', 'children')[0]
    c = p.dig('children')[0]
    assert_equal(h.parent(c), p, "Child #{c['name']} parent is #{p['name']}")
    assert_equal(h.parent({}).nil?, true, 'Other object has no parent')
    assert_equal(h.parent(d.keys[0]).nil?, true, 'Keys have no parent')
    assert_equal(h.parent(d.dig('children', 'name')).nil?, true, 'String value has no parent')
  end

  def test_category_and_name
    d = doc1
    h = Helper.new(d)
    assert_equal(h.category_and_name([]).nil?, true, 'Not string')
    assert_equal(h.category_and_name({ '$ref' => 1 }).nil?, true, 'ref not string')
    assert_equal(h.category_and_name('not_ref').nil?, true, 'Not reference string')
    assert_equal(h.category_and_name({ '$ref' => 'not_ref' }).nil?, true, 'ref not reference string')
    assert_equal(h.category_and_name('#/components/nothing').nil?, true, 'Not reference string')
    cat, name = h.category_and_name('#/components/cat/name')
    assert_equal(cat, 'cat', 'category found')
    assert_equal(name, 'name', 'name found')
    cat, name = h.category_and_name({ '$ref' => '#/components/cat/name' })
    assert_equal(cat, 'cat', 'category found again')
    assert_equal(name, 'name', 'name found again')
  end

  def doc2
    YAML.safe_load(%(
---
components:
  category:
    name: 5
))
  end

  def test_dereference
    d = doc2
    h = Helper.new(d)
    assert_equal(h.dereference('invalid').nil?, true, 'invalid')
    assert_equal(h.dereference('#/components/missing/name').nil?, true, 'no category')
    assert_equal(h.dereference('#/components/category/missing').nil?, true, 'no name')
    assert_equal(h.dereference('#/components/category/name'), 5, 'valid')
  end

  def test_basename
    d = doc2
    h = Helper.new(d)
    assert_equal(h.basename('invalid').nil?, true, 'invalid')
    assert_equal(h.basename('#/components/partial').nil?, true, 'missing part')
    assert_equal(h.basename('#/components/cat/name'), 'name', 'name returned')
  end

  def doc3
    YAML.safe_load(%(
---
paths:
  "/no/parameter":
    put:
      something: else
    get:
      parameters:
      - "$ref": "#/components/parameters/param3"
  "/parent/parameter":
    parameters:
    - "$ref": "#/components/parameters/param1"
    put:
      something: else
    get:
      parameters:
      - "$ref": "#/components/parameters/param2"
components:
  parameters:
    param1:
      name: param1
      in: query
    param2:
      name: param2
      in: path
    param3:
      name: param3
      in: header
))
  end

  def test_parameters
    d = doc3
    h = Helper.new(d)
    cp = d.dig('components', 'parameters')
    p = h.parameters(d.dig('paths', '/no/parameter', 'put'))
    assert_equal(p.empty?, true, 'no parameters')
    p = h.parameters(d.dig('paths', '/no/parameter', 'get'))
    assert_equal(p.size, 1, 'one parameter')
    assert_equal(p.first['$ref'].end_with?("/#{cp.dig('param3', 'name')}"), true, 'name matches')
    p = h.parameters(d.dig('paths', '/parent/parameter', 'put'))
    assert_equal(p.size, 1, 'one parameter')
    assert_equal(p.first['$ref'].end_with?("/#{cp.dig('param1', 'name')}"), true, 'name matches')
    p = h.parameters(d.dig('paths', '/parent/parameter', 'get'))
    assert_equal(p.size, 2, 'two parameters')
    assert_equal(p.first['$ref'].end_with?("/#{cp.dig('param1', 'name')}"), true, 'name matches')
    assert_equal(p.last['$ref'].end_with?("/#{cp.dig('param2', 'name')}"), true, 'name matches')
    p = h.parameters(d.dig('paths', '/parent/parameter', 'put'), true)
    assert_equal(p.empty?, true, 'no local parameters')
    p = h.parameters(d.dig('paths', '/no/parameter', 'put'), true)
    assert_equal(p.empty?, true, 'no local parameters')
  end

  def doc4
    YAML.safe_load(%(
---
responses:
  '400':
    description: Bad Request
  '500':
    description: Internal Server Error
  default:
    description: Default response
  '2xx':
    description: Success
  '3XX':
    description: Redirect
  '200':
    description: 'Specific success'
))
  end

  def test_response_codes
    d = doc4
    h = Helper.new(d)
    r = h.response_codes(d['responses'])
    assert_equal(r, ['200', '400', '500', '2xx', '3XX', 'default'], 'correct order')
    r = h.response_codes({ '200' => 'thing' })
    assert_equal(r, ['200'], 'single response code')
    r = h.response_codes({})
    assert_equal(r, [], 'empty responses object')
  end

  def test_response_code_condition
    d = doc4
    h = Helper.new(d)
    assert_equal(h.response_code_condition('200'), 'code == 200', 'exact match')
    assert_equal(h.response_code_condition('201', op_eq: 'eq', var: 'v'), 'v eq 201', 'var/eq/exact')
    assert_equal(h.response_code_condition('2xx', var: 'foo'), '(200 <= foo) && (foo <= 299)', 'var/range')
    assert_equal(h.response_code_condition('3XX', op_and: 'and'), '(300 <= code) and (code <= 399)', 'and/range')
    assert_equal(h.response_code_condition('40x', op_lte: '.lte.'), '(400 .lte. code) && (code .lte. 409)', 'lte/range')
  end
end
