#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require 'yaml'
include Test::Unit::Assertions

load '../bin/openapi-patterntests'

class PatternTestsTest < Test::Unit::TestCase
  def test_key
    assert_equal(key({ 'pattern' => '^abc$', 'minLength' => 3, 'maxLength' => 5 }), '^abc$::3::5', 'both lengths')
    assert_equal(key({ 'pattern' => '^abc$', 'maxLength' => 5 }), '^abc$::0::5', 'default min')
    assert_equal(key({ 'pattern' => '^abc$', 'minLength' => 2 }), '^abc$::2::inf', 'default max')
  end

  def test_find_patterns
    d = { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6, 'other' => 'foo' }
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::1::6'], { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6 }, 'no extras')
    d = { 'pattern' => 'patstr', 'maxLength' => 6 }
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::0::6'], d, 'missing min')
    d = { 'pattern' => 'patstr', 'minLength' => 1 }
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::1::inf'], d, 'missing max')
    p0 = { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6, 'other' => 'foo' }
    p1 = { 'pattern' => 'patstr', 'maxLength' => 6 }
    d = [ p0, p1 ]
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::1::6'], { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6 }, 'no extras from array')
    assert_equal(r['patstr::0::6'], p1, 'missing min from array')
    d = { 'key' => p0, 'key2' => { 'key2' => p1 } }
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::1::6'], { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6 }, 'no extras deeper')
    assert_equal(r['patstr::0::6'], p1, 'missing min deeper')
    d = { 'key' => p0, 'patternProperties' => { 'propPat' => p1, 'propPat2' => [] } }
    r = {}
    find_patterns(d, r)
    assert_equal(r['patstr::1::6'], { 'pattern' => 'patstr', 'minLength' => 1, 'maxLength' => 6 }, 'no extras deeper')
    assert_equal(r['patstr::0::6'], p1, 'missing min under patternProperties')
    assert_equal(r['propPat::0::inf'], { 'pattern' => 'propPat' }, 'property pattern')
    assert_equal(r['propPat2::0::inf'], { 'pattern' => 'propPat2' }, 'property pattern 2')
  end

  def test_pattern_list2hash
    p0 = { 'pattern' => 'dsfkjh', 'minLength' => 1, 'maxLength' => 6 }
    p1 = { 'pattern' => 'qewiuh', 'maxLength' => 6 }
    list = [ p0, p1 ]
    r = pattern_list2hash(list)
    assert_equal(r.size, list.size, 'same number of elements')
    list.each do |item|
      assert_equal(r[key(item)], item, "#{item['pattern']} is present")
    end
  end

  def test_add_strings
    p0 = { 'pattern' => 'dsfkjh', 'minLength' => 1, 'maxLength' => 6 }
    add_strings(p0)
    assert_equal(p0.key?('pass'), true, 'has pass')
    assert_equal(p0.key?('fail'), true, 'has fail')
    assert_equal(p0['fail'].size, 2, 'too short and too long')
    assert_equal(p0['fail'].index('').nil?, false, 'empty string fails')
    assert_equal(p0['fail'].index { |s| s.size > p0['maxLength'] }.nil?, false, 'too long string fails')
    assert_equal(p0['pass'].empty?, true, 'passing ones empty')
  end

  def test_merge_arrays
    a = [ 1, 2, 3 ]
    b = [ 4, 5, 6 ]
    r = merge_arrays(a, b)
    assert_equal(r, a.concat(b), 'concatenates arrays')
    r = merge_arrays(false, b)
    assert_equal(r, b, 'returns second array if first is false')
    r = merge_arrays(a, false)
    assert_equal(r, a, 'returns first array if second is false')
    r = merge_arrays(false, false)
    assert_equal(r, false, 'returns false if both are false')
  end

  def test_merge_existing
    p0 = { 'pattern' => 'qewiuh', 'maxLength' => 6, 'pass' => [ 'qewiuh' ], 'fail' => false }
    pmms = {
      'p0' => p0,
      'p1' => { 'pattern' => 'dsfkjh', 'minLength' => 1, 'maxLength' => 6, 'pass' => [ 'a' ] }
    }
    existing = { 'p1' => { 'pass' => [ 'a', 'b' ], 'fail' => [ 'c', 'd' ] } }
    merge_existing(pmms, existing)
    assert_equal(pmms['p1']['pass'], [ 'a', 'b' ], 'merges pass arrays')
    assert_equal(pmms['p1']['fail'], [ 'c', 'd' ], 'places fail array')
    assert_equal(pmms['p1']['minLength'], 1, 'preserves minLength')
    assert_equal(pmms['p1']['maxLength'], 6, 'preserves maxLength')
    assert_equal(pmms['p1']['pattern'], 'dsfkjh', 'preserves pattern')
    assert_equal(pmms['p0'], p0, 'stayed unchanged')
  end

  def test_add_removed
    pmms = { 'key' => 'value', 'other_key' => 'other_value' }
    existing = { 'previous' => 'prev', 'key' => 'previous_value' }
    add_removed(pmms, existing)
    assert_equal(pmms.size, 3, 'one key added')
    assert_equal(pmms['key'], 'value', 'key unchanged')
    assert_equal(pmms['other_key'], 'other_value', 'other_key unchanged')
    assert_equal(pmms['previous'], 'prev', 'previous added')
  end

  def test_compare
    a = { 'pattern' => 'asorfhs', 'minLength' => 1, 'maxLength' => 10 }
    b = { 'pattern' => 'beofhrs', 'minLength' => 2, 'maxLength' => 10 }
    assert_equal(compare(a, b), -1, 'a pattern string is before b')
    assert_equal(compare(b, a), 1, 'b pattern string is after a')
    assert_equal(compare(b, b), 0, 'b equals b')
    b = { 'pattern' => 'asorfhs', 'minLength' => 2, 'maxLength' => 10 }
    assert_equal(compare(a, b), -1, 'a can be shorter than b')
    assert_equal(compare(b, a), 1, 'b minimum is greater than a')
    b = { 'pattern' => 'asorfhs', 'minLength' => 1, 'maxLength' => 11 }
    assert_equal(compare(a, b), -1, 'b can be longer than a')
    assert_equal(compare(b, a), 1, 'b maximum is greater than a')
    a = { 'pattern' => 'asorfhs' }
    b = { 'pattern' => 'asorfhs' }
    assert_equal(compare(a, b), 0, 'Same defaults for both')
  end

  def test_pattern_hash2list
    p1 = { 'pattern' => 'dsfkjh', 'minLength' => 1, 'maxLength' => 6 }
    p2 = { 'pattern' => 'qewiuh', 'maxLength' => 6 }
    p0 = { 'pattern' => 'aosihd', 'maxLength' => 6 }
    list = pattern_hash2list({ 'key' => p1, 'key2' => p2, 'key3' => p0 })
    assert_equal(list[0], p0, 'p0 should be first')
    assert_equal(list[1], p1, 'p1 should be second')
    assert_equal(list[2], p2, 'p2 should be third')
    assert_equal(compare(list[0], list[1]), -1, 'two first in order')
    assert_equal(compare(list[1], list[2]), -1, 'two last in order')
  end
end
