#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2024-2026 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'test/unit'
require_relative '../lib/openapi/sourcetools/docs'
include Test::Unit::Assertions

class DocsTest < Test::Unit::TestCase
  def test_add
    d = OpenAPISourceTools::Docs.new
    assert_equal(d.add('name', 'content'), true, 'Added name')
    begin
      assert_equal(d.name, 'content', 'Stored ok')
    rescue Exception => e
      assert_equal(true, false, "Exception thrown #{e}")
    end
    assert_equal(d.add('name', 'sdhfaksdjhfskj'), false, 'Not added')
    begin
      assert_equal(d.name, 'content', 'Stored still ok')
    rescue Exception => e
      assert_equal(true, false, "Exception thrown #{e}")
    end
    begin
      d.unset = 'value'
    rescue Exception => e
      assert_equal(true, true, "Unset name")
    end
  end
end
