AllCops:
  NewCops: enable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false
Style/StderrPuts:
  Enabled: false
